name: test_dimy_tech
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  rxdart: ^0.27.4
  google_fonts: ^3.0.1
  http: ^0.13.4
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.1
  readmore: ^2.2.0
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
